import{useMemo,useState}from'react';

type Product={id:number;name:string;category:string;price:string;moq:string;image:string;source:string;description:string;specs:string[];supplier:string;address:string;url:string;unlock:number};
const products:Product[]=[
{id:1,name:'Portable Power Station 1000W',category:'Solar & Renewable Energy',price:'$280–$360',moq:'10 units',image:'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80',source:'Alibaba',description:'Portable LiFePO4 power station for home backup, camping and small business use.',specs:['1000W continuous output','LiFePO4 battery','Pure sine wave','AC / USB / DC outputs'],supplier:'Shenzhen PowerTech Energy Co., Ltd.',address:'Longhua District, Shenzhen, Guangdong, China',url:'https://www.alibaba.com/',unlock:9.99},
{id:2,name:'Solar Street Light 200W',category:'Solar & Renewable Energy',price:'$38–$62',moq:'50 units',image:'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',source:'Made-in-China',description:'All-in-one solar street lighting solution for roads, compounds and commercial projects.',specs:['200W LED','Integrated solar panel','Lithium battery','IP65 weather resistant'],supplier:'Guangzhou BrightSolar Technology Co., Ltd.',address:'Baiyun District, Guangzhou, Guangdong, China',url:'https://www.made-in-china.com/',unlock:7.99},
{id:3,name:'TWS Bluetooth Earbuds',category:'Electronics',price:'$4.80–$8.50',moq:'100 units',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80',source:'1688',description:'Compact wireless earbuds suitable for retail, private label and promotional orders.',specs:['Bluetooth 5.x','Charging case','Touch controls','OEM packaging available'],supplier:'Shenzhen AudioLink Electronics Co., Ltd.',address:'Bao’an District, Shenzhen, Guangdong, China',url:'https://www.1688.com/',unlock:5.99},
{id:4,name:'Electric Kitchen Blender',category:'Home & Kitchen',price:'$16–$24',moq:'30 units',image:'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=900&q=80',source:'Global Sources',description:'High-speed countertop blender for home and commercial kitchen markets.',specs:['1200W motor','Multiple speed settings','Stainless steel blades','OEM branding'],supplier:'Ningbo HomePro Appliances Co., Ltd.',address:'Ningbo, Zhejiang, China',url:'https://www.globalsources.com/',unlock:6.99}];

function App(){const[page,setPage]=useState('home');const[q,setQ]=useState('');const[cat,setCat]=useState('All');const[selected,setSelected]=useState<Product|null>(null);const[unlocked,setUnlocked]=useState<number[]>([]);const[admin,setAdmin]=useState(false);const[notice,setNotice]=useState('');
const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&(p.name+p.category+p.description).toLowerCase().includes(q.toLowerCase())),[q,cat]);
const go=(p:string)=>{setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
const unlock=(p:Product)=>{setSelected(p);setUnlocked(u=>u.includes(p.id)?u:u.concat(p.id));setNotice(`Demo unlock recorded for ${p.name}. Connect your payment gateway before accepting real payments.`);setTimeout(()=>setNotice(''),5000)};
return <div className="app"><header><div className="brand" onClick={()=>go('home')}><span className="logo">CS</span><div><b>ChinaSource Hub</b><small>Global China Sourcing</small></div></div><nav><button onClick={()=>go('products')}>Products</button><button onClick={()=>go('services')}>Services</button><button onClick={()=>go('how')}>How it works</button><button onClick={()=>go('request')}>Request a Quote</button></nav><button className="admin" onClick={()=>setAdmin(!admin)}>{admin?'Customer View':'Admin'}</button></header>
{notice&&<div className="notice">{notice}</div>}
{admin?<Admin go={go}/>:page==='home'?<Home go={go}/>:page==='products'?<Products filtered={filtered} q={q} setQ={setQ} cat={cat} setCat={setCat} open={setSelected}/>:page==='services'?<Services/>:page==='how'?<How/>:<Request/>}
{selected&&<Modal p={selected} unlocked={unlocked.includes(selected.id)} close={()=>setSelected(null)} unlock={unlock}/>}<footer><div><b>ChinaSource Hub</b><p>Your bridge to reliable China sourcing for buyers worldwide.</p></div><div><b>Explore</b><p>Products · Services · Supplier research · RFQ</p></div><div><b>Important</b><p>Supplier details are released only after access payment. Prices and availability are indicative.</p></div></footer></div>}

function Home({go}:{go:(p:string)=>void}){return <><section className="hero"><div><span className="eyebrow">GLOBAL SOURCING · CHINA</span><h1>Discover products from China. <em>Source with confidence.</em></h1><p>Browse curated products, compare sourcing opportunities and unlock supplier information when you are ready to buy.</p><div className="actions"><button className="primary" onClick={()=>go('products')}>Browse Products →</button><button className="secondary" onClick={()=>go('request')}>Request a Product</button></div><div className="trust"><span>✓ Global buyers</span><span>✓ Supplier research</span><span>✓ Transparent pricing</span></div></div><div className="heroCard"><div className="mini">FEATURED SOURCING</div><h3>Portable Power Station</h3><p>Indicative supplier price</p><strong>$280–$360</strong><hr/><span>MOQ 10 · Shenzhen · OEM available</span><button onClick={()=>go('products')}>View product</button></div></section><section className="section"><div className="sectionHead"><div><span className="eyebrow">PRODUCT CATALOG</span><h2>Source-ready products</h2></div><button onClick={()=>go('products')}>View all →</button></div><div className="grid">{products.slice(0,3).map(p=><ProductCard key={p.id} p={p} open={()=>{}} detail={()=>{go('products')}}/>)}</div></section><section className="band"><div><span className="eyebrow">WHY CHINASOURCE HUB</span><h2>We protect the value of supplier research.</h2></div><p>Customers can explore product opportunities without exposing the original supplier identity. When a buyer decides the product is worth pursuing, they can pay for supplier access and continue to the original marketplace listing.</p></section></>}
function Products({filtered,q,setQ,cat,setCat,open}:{filtered:Product[];q:string;setQ:(x:string)=>void;cat:string;setCat:(x:string)=>void;open:(p:Product)=>void}){const cats=['All',...Array.from(new Set(products.map(p=>p.category)))];return <main className="page"><div className="pageHead"><span className="eyebrow">PRODUCT CATALOG</span><h1>China-sourced products</h1><p>Explore opportunities from major Chinese sourcing marketplaces. Supplier identity and direct links stay private until access is unlocked.</p></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/><select value={cat} onChange={e=>setCat(e.target.value)}>{cats.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid">{filtered.map(p=><ProductCard key={p.id} p={p} open={()=>open(p)} detail={()=>open(p)}/>)}</div></main>}
function ProductCard({p,open,detail}:{p:Product;open:()=>void;detail:()=>void}){return <article className="card"><img src={p.image}/><div className="cardBody"><span className="tag">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="meta"><span><b>{p.price}</b><small> indicative</small></span><span>MOQ {p.moq}</span></div><div className="private">🔒 Supplier details protected</div><button className="primary full" onClick={open}>View & Unlock Supplier</button></div></article>}
function Modal({p,unlocked,close,unlock}:{p:Product;unlocked:boolean;close:()=>void;unlock:(p:Product)=>void}){return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><img src={p.image}/><div className="modalText"><span className="tag">{p.source} · {p.category}</span><h2>{p.name}</h2><p>{p.description}</p><h4>Key specifications</h4><ul>{p.specs.map(s=><li key={s}>{s}</li>)}</ul><div className="supplierBox">{unlocked?<><b>Supplier access unlocked</b><p><strong>{p.supplier}</strong><br/>{p.address}</p><a href={p.url} target="_blank" rel="noreferrer">Open original supplier marketplace →</a></>:<><b>Supplier identity protected</b><p>The supplier name, address and direct marketplace listing are hidden from public catalog visitors.</p><button className="primary full" onClick={()=>unlock(p)}>Unlock Supplier Access · ${p.unlock}</button><small>Demo payment only — connect a real payment provider before launch.</small></>}</div></div></div></div>}
function Services(){return <main className="page"><div className="pageHead"><span className="eyebrow">SERVICES</span><h1>From product discovery to supplier access.</h1></div><div className="serviceGrid">{['Supplier Research','Product Sourcing','Price Negotiation','Supplier Verification','Sample Ordering','OEM / ODM','Quality Inspection','Shipping Coordination'].map((x,i)=><div className="service" key={x}><span>0{i+1}</span><h3>{x}</h3><p>Professional support for international buyers sourcing products from China.</p></div>)}</div></main>}
function How(){return <main className="page"><div className="pageHead"><span className="eyebrow">HOW IT WORKS</span><h1>A simple path from idea to supplier.</h1></div><div className="steps">{[['01','Browse','Explore products and sourcing opportunities without exposing supplier identity.'],['02','Evaluate','Review indicative price, MOQ, specifications and category information.'],['03','Unlock','Pay the supplier-information access fee when you are ready.'],['04','Buy direct','Receive supplier details and the original marketplace page so you can continue the purchase.']].map(s=><div className="step" key={s[0]}><b>{s[0]}</b><h3>{s[1]}</h3><p>{s[2]}</p></div>)}</div></main>}
function Request(){return <main className="page"><div className="pageHead"><span className="eyebrow">REQUEST A QUOTE</span><h1>Tell us what you want to source.</h1><p>For products not yet in the catalog, submit a sourcing request and our team can research suitable Chinese suppliers.</p></div><form className="form" onSubmit={e=>{e.preventDefault();alert('Request submitted. Connect this form to your database/email service for production use.')}}><label>Product name<input required placeholder="e.g. 500 solar street lights"/></label><label>Destination country<input required placeholder="e.g. United States"/></label><label>Quantity<input required type="number" placeholder="500"/></label><label>Target budget<input placeholder="USD 5,000"/></label><label className="wide">Requirements<textarea rows={5} placeholder="Specifications, colors, packaging, certifications, customization..."/></label><button className="primary wide">Submit Sourcing Request</button></form></main>}
function Admin({go}:{go:(p:string)=>void}){return <main className="page"><div className="adminHead"><div><span className="eyebrow">ADMIN</span><h1>Product Catalog Manager</h1><p>Private supplier data is stored in the admin layer, not displayed in public cards.</p></div><button className="primary" onClick={()=>alert('Product creation form is ready to connect to your database/storage.')}>+ Add Product</button></div><div className="adminTable">{products.map(p=><div className="row" key={p.id}><img src={p.image}/><div><b>{p.name}</b><small>{p.source} · {p.category}</small></div><span>{p.price}</span><span>MOQ {p.moq}</span><span className="green">Private</span><button onClick={()=>go('products')}>Preview</button></div>)}</div><div className="security"><b>🔐 Production security requirement</b><p>Keep supplier address, supplier name and original listing URL in a server-side database. Never send private supplier fields to the public product API before payment authorization is confirmed.</p></div></main>}
export default App;