import {useEffect,useMemo,useState} from 'react';
import {products, type Product} from './products';

type SupplierInfo={supplier:string;address:string;url:string};
type Currency=string;
const PAGE_SIZE=24;
const FALLBACK_RATES:Record<string,number>={USD:1/153,ETB:1,EUR:1/180,GBP:1/210,AED:1/42,CNY:1/21};
const CURRENCY_CODES=['USD','ETB','EUR','GBP','AED','CNY','AFN','ALL','AMD','ANG','AOA','ARS','AUD','AWG','AZN','BAM','BBD','BDT','BGN','BHD','BIF','BMD','BND','BOB','BRL','BSD','BTN','BWP','BYN','BZD','CAD','CDF','CHF','CLP','COP','CRC','CUP','CVE','CZK','DJF','DKK','DOP','DZD','EGP','ERN','ETB','EUR','FJD','FKP','FOK','GEL','GGP','GHS','GIP','GMD','GNF','GTQ','GYD','HKD','HNL','HRK','HTG','HUF','IDR','ILS','IMP','INR','IQD','IRR','ISK','JEP','JMD','JOD','JPY','KES','KGS','KHR','KID','KMF','KRW','KWD','KYD','KZT','LAK','LBP','LKR','LRD','LSL','LYD','MAD','MDL','MGA','MKD','MMK','MNT','MOP','MRU','MUR','MVR','MWK','MXN','MYR','MZN','NAD','NGN','NIO','NOK','NPR','NZD','OMR','PAB','PEN','PGK','PHP','PKR','PLN','PYG','QAR','RON','RSD','RUB','RWF','SAR','SBD','SCR','SDG','SEK','SGD','SHP','SLE','SLL','SOS','SRD','SSP','STN','SYP','SZL','THB','TJS','TMT','TND','TOP','TRY','TTD','TVD','TWD','TZS','UAH','UGX','USD','UYU','UZS','VES','VND','VUV','WST','XAF','XCD','XOF','XPF','YER','ZAR','ZMW','ZWL'];
const validCurrency=(value:string|null,rates:Record<string,number>):Currency=>value&&rates[value]!==undefined?value:'USD';
function currencySymbol(code:string){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:code,currencyDisplay:'narrowSymbol',maximumFractionDigits:0}).formatToParts(0).find(p=>p.type==='currency')?.value||code}catch{return code}}
function priceInCurrency(price:string,currency:Currency,rates:Record<string,number>){
  const rate=rates[currency];
  if(rate===undefined)return price;
  const matches=price.match(/\d[\d,]*(?:\.\d+)?/g)||[];
  const amounts=matches.map(v=>Number(v.replace(/,/g,''))).filter(Number.isFinite);
  if(!amounts.length)return price;
  const digits=['JPY','KRW','VND','IDR','CLP','PYG','UGX','TZS','RWF','GNF','KMF','XAF','XOF','XPF'].includes(currency)?0:2;
  const formatted=amounts.map(amount=>(amount*rate).toLocaleString(undefined,{minimumFractionDigits:digits,maximumFractionDigits:digits}));
  const symbol=currencySymbol(currency);
  return `${symbol}${formatted.join(`-${symbol}`)}`;
}

export default function App(){
  const[page,setPage]=useState('home'),[q,setQ]=useState(''),[cat,setCat]=useState('All'),[pageNo,setPageNo]=useState(1),[selected,setSelected]=useState<Product|null>(null),[info,setInfo]=useState<SupplierInfo|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),[currency,setCurrency]=useState<Currency>('USD'),[rates,setRates]=useState<Record<string,number>>(FALLBACK_RATES);
  const categories=useMemo(()=>['All',...Array.from(new Set(products.map(p=>p.category)))],[]);
  const currencies=useMemo(()=>Array.from(new Set(Object.keys(rates).filter(code=>CURRENCY_CODES.includes(code)).concat(CURRENCY_CODES.filter(code=>rates[code]!==undefined)))).sort(),[rates]);
  const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&(p.name+p.category).toLowerCase().includes(q.toLowerCase())),[q,cat]);
  const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));
  const visible=filtered.slice((pageNo-1)*PAGE_SIZE,pageNo*PAGE_SIZE);
  useEffect(()=>{setPageNo(1)},[q,cat]);
  useEffect(()=>{try{const saved=localStorage.getItem('currency');if(saved)setCurrency(validCurrency(saved,FALLBACK_RATES))}catch{};fetch('https://open.er-api.com/v6/latest/ETB').then(r=>r.ok?r.json():null).then(data=>{if(data?.rates){setRates(data.rates);try{const saved=localStorage.getItem('currency');if(saved&&data.rates[saved]!==undefined)setCurrency(saved)}catch{}}}).catch(()=>{})},[]);
  useEffect(()=>{try{localStorage.setItem('currency',currency)}catch{}},[currency]);
  useEffect(()=>{const x=new URLSearchParams(location.search),id=x.get('productId'),sid=x.get('session_id');if(x.get('payment')==='success'&&id&&sid){setLoading(true);fetch('/api/unlock-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id,sessionId:sid})}).then(r=>r.json()).then(d=>{if(d.supplier){setInfo(d);setSelected(products.find(p=>String(p.id)===id)||null);setNotice('Payment verified — supplier access unlocked.')}else setNotice(d.error||'Payment verification failed.')}).catch(()=>setNotice('Payment verification failed.')).finally(()=>setLoading(false));}if(x.get('payment')==='cancelled')setNotice('Payment cancelled. No supplier information was unlocked.')},[]);
  const go=(x:string)=>setPage(x);
  const checkout=async(p:Product)=>{setLoading(true);try{const r=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:p.id})});const d=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url}catch(e){setNotice(e instanceof Error?e.message:'Checkout failed');setLoading(false)}};
  const currencyName=(code:string)=>{try{return new Intl.DisplayNames([navigator.language||'en'],{type:'currency'}).of(code)||code}catch{return code}};
  return <div className="app"><header><div className="brand" onClick={()=>go('home')}><span className="logo">CS</span><div><b>ChinaSource Hub</b><small>Global China Sourcing</small></div></div><nav><button onClick={()=>go('products')}>Products</button><button onClick={()=>go('services')}>Services</button><button onClick={()=>go('how')}>How it works</button><button onClick={()=>go('request')}>Request a Quote</button></nav><div style={{display:'flex',alignItems:'center',gap:8,marginLeft:'auto'}}><span style={{fontSize:12,fontWeight:700,opacity:.7}}>Currency</span><select aria-label="Choose currency" value={currency} onChange={e=>setCurrency(validCurrency(e.target.value,rates))} style={{padding:'8px 10px',borderRadius:8,border:'1px solid #d8dce3',background:'#fff',fontWeight:700,cursor:'pointer',maxWidth:180}}>{currencies.map(code=><option key={code} value={code}>{currencySymbol(code)} {code} — {currencyName(code)}</option>)}</select></div></header>
    {notice&&<div className="notice">{notice}<button onClick={()=>setNotice('')} style={{marginLeft:12,border:0,background:'transparent',color:'#fff'}}>×</button></div>}{loading&&<div className="notice">Processing securely…</div>}
    {page==='home'?<Home go={go} currency={currency} rates={rates}/>:page==='products'?<main className="page"><div className="pageHead"><span className="eyebrow">PRODUCT CATALOG · {products.length} LISTINGS</span><h1>China-sourced products</h1><p>Browse the actual products imported from the uploaded Alibaba catalog. Supplier identity and direct links stay private until verified payment.</p></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/><select value={cat} onChange={e=>setCat(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></div><div className="grid">{visible.map(p=><Card key={p.id} p={p} currency={currency} rates={rates} open={()=>{setInfo(null);setSelected(p)}}/>)}</div><Pagination page={pageNo} total={totalPages} setPage={setPageNo}/></main>:page==='services'?<Services/>:page==='how'?<How/>:<Request/>}
    {selected&&<Modal p={selected} info={info} currency={currency} rates={rates} close={()=>{setSelected(null);setInfo(null)}} checkout={checkout}/>}<footer><b>ChinaSource Hub</b><p>Your bridge to China sourcing for buyers worldwide.</p></footer></div>
}
function Home({go,currency,rates}:{go:(x:string)=>void;currency:Currency;rates:Record<string,number>}){return <><section className="hero"><div><span className="eyebrow">GLOBAL SOURCING · CHINA</span><h1>Discover products from China. <em>Source with confidence.</em></h1><p>Browse 240 real Alibaba listings from the imported catalog, compare opportunities, then unlock supplier access when you are ready to buy.</p><div className="actions"><button className="primary" onClick={()=>go('products')}>Browse Products →</button><button className="secondary" onClick={()=>go('how')}>How it works</button></div><div className="trust"><span>✓ Real catalog listings</span><span>✓ Supplier details protected</span><span>✓ $2.50 per unlock</span></div></div><div className="heroCard"><span className="mini">SOURCE ACCESS</span><h3>One catalog. Supplier access when you need it.</h3><strong>$2.50</strong><span> per supplier unlock</span><hr/><span>Product prices display in {currency}. Unlock fee remains $2.50 USD.</span><button onClick={()=>go('products')}>Explore 240 products →</button></div></section><section className="section"><div className="sectionHead"><div><span className="eyebrow">CATALOG HIGHLIGHTS</span><h2>Source-ready products</h2></div><button onClick={()=>go('products')}>View all 240 →</button></div><div className="grid">{products.slice(0,6).map(p=><Card key={p.id} p={p} currency={currency} rates={rates} open={()=>go('products')}/>)}</div></section></>}
function Card({p,open,currency,rates}:{p:Product;open:()=>void;currency:Currency;rates:Record<string,number>}){return <article className="card">{p.bigDeal&&<div className="dealBadge">🔥 BIG DEAL</div>}<img src={p.image} alt={p.name}/><div className="cardBody"><span className="tag">{p.category}</span><h3>{p.name}</h3><p>Supplier-listed product from the imported Alibaba catalog.</p><div className="meta"><b>{priceInCurrency(p.price,currency,rates)}</b><span>{p.moq}</span></div><div className="private">🔒 Supplier details protected</div><button className="primary full" onClick={open}>View & Unlock Supplier</button></div></article>}
function Pagination({page,total,setPage}:{page:number;total:number;setPage:(n:number)=>void}){if(total<=1)return null;const start=Math.max(1,Math.min(total-6,page-3));const nums=Array.from({length:Math.min(7,total)},(_,i)=>start+i);return <div style={{display:'flex',justifyContent:'center',gap:8,marginTop:30,flexWrap:'wrap'}}><button className="secondary" disabled={page===1} onClick={()=>setPage(page-1)}>← Prev</button>{nums.map(n=><button key={n} className={n===page?'primary':'secondary'} onClick={()=>setPage(n)}>{n}</button>)}<button className="secondary" disabled={page===total} onClick={()=>setPage(page+1)}>Next →</button></div>}
function Modal({p,info,close,checkout,currency,rates}:{p:Product;info:SupplierInfo|null;close:()=>void;checkout:(p:Product)=>void;currency:Currency;rates:Record<string,number>}){return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><img src={p.image} alt={p.name}/><div className="modalText">{p.bigDeal&&<div className="dealBadge inline">🔥 BIG DEAL</div>}<span className="tag">{p.source} · {p.category}</span><h2>{p.name}</h2><p>Supplier-listed product from the imported Alibaba catalog.</p><div className="meta" style={{marginBottom:18}}><b>{priceInCurrency(p.price,currency,rates)}</b><span>{p.moq}</span></div><div className="supplierBox">{info?<><b>✓ Supplier access unlocked</b><p><strong>{info.supplier}</strong><br/>{info.address}</p><a href={info.url} target="_blank" rel="noreferrer">Open original Alibaba listing →</a></>:<><b>Supplier identity protected</b><p>Supplier name, address and direct listing are hidden until your payment is verified.</p><button className="primary full" onClick={()=>checkout(p)}>Pay $2.50 USD · Unlock Supplier</button><small>Secure payment powered by Stripe.</small></>}</div></div></div></div>}
function Services(){return <main className="page"><div className="pageHead"><span className="eyebrow">SERVICES</span><h1>From product discovery to supplier access.</h1><p>We help buyers identify China sourcing opportunities, compare supplier listings, and access the original supplier listing after payment verification.</p></div><div className="serviceGrid"><div className="service"><span>01</span><h3>Product discovery</h3><p>Browse the imported catalog and search by product name or category.</p></div><div className="service"><span>02</span><h3>Supplier research</h3><p>We keep supplier identity private until the buyer chooses to unlock it.</p></div><div className="service"><span>03</span><h3>Direct access</h3><p>After verified payment, the original Alibaba listing is returned.</p></div><div className="service"><span>04</span><h3>Custom sourcing</h3><p>Need something not listed? Request a sourcing search for a specific product.</p></div></div></main>}
function How(){return <main className="page"><div className="pageHead"><span className="eyebrow">HOW IT WORKS</span><h1>Browse → Evaluate → Pay → Buy direct</h1><p>Supplier details are not exposed in the public catalog.</p></div><div className="steps"><div className="step"><b>1</b><h3>Browse</h3><p>Search the 240 imported Alibaba listings.</p></div><div className="step"><b>2</b><h3>Evaluate</h3><p>Review the product, displayed price, MOQ and source information.</p></div><div className="step"><b>3</b><h3>Unlock</h3><p>Pay $2.50 securely through Stripe.</p></div><div className="step"><b>4</b><h3>Buy direct</h3><p>Once payment is verified, supplier information and the original listing link are shown.</p></div></div></main>}
function Request(){return <main className="page"><div className="pageHead"><span className="eyebrow">REQUEST A QUOTE</span><h1>Tell us what you want to source.</h1><p>Describe the product, quantity, target price and destination. We can research suitable Chinese supplier listings.</p></div><div className="form"><label>Product name<input placeholder="e.g. rechargeable LED lamps"/></label><label>Quantity<input placeholder="e.g. 500 units"/></label><label>Target price<input placeholder="e.g. under $8 per unit"/></label><label>Destination<input placeholder="Country / city"/></label><label className="wide">Requirements<textarea rows={6} placeholder="Specifications, packaging, branding, certifications, etc."/></label><button className="primary" type="button" onClick={()=>alert('Request form ready — connect it to your email or CRM when you are ready.')}>Submit sourcing request</button></div></main>}
