import {useEffect,useMemo,useState} from 'react';
type P={id:number;name:string;category:string;price:string;moq:string;image:string;source:string;description:string;specs:string[];unlock:number;bigDeal?:boolean};type I={supplier:string;address:string;url:string};
const memoryImg='https://s.alicdn.com/@sc04/kf/H6c1f949b74dc401ca45fddeacd6e0a6fU.png_720x720q50.png';
const products:P[]=[
{id:1,name:'Portable Power Station 1000W',category:'Solar & Renewable Energy',price:'$280–$360',moq:'10 units',image:'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?auto=format&fit=crop&w=900&q=80',source:'Alibaba',description:'Portable LiFePO4 power station for home backup, camping and small business use.',specs:['1000W output','LiFePO4 battery','Pure sine wave','AC / USB / DC'],unlock:2.5},
{id:2,name:'Solar Street Light 200W',category:'Solar & Renewable Energy',price:'$38–$62',moq:'50 units',image:'https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=900&q=80',source:'Made-in-China',description:'All-in-one solar street lighting for roads, compounds and commercial projects.',specs:['200W LED','Integrated panel','Lithium battery','IP65'],unlock:2.5},
{id:3,name:'TWS Bluetooth Earbuds',category:'Electronics',price:'$4.80–$8.50',moq:'100 units',image:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=900&q=80',source:'1688',description:'Compact wireless earbuds for retail, private label and promotional orders.',specs:['Bluetooth 5.x','Charging case','Touch controls','OEM packaging'],unlock:2.5},
{id:4,name:'Electric Kitchen Blender',category:'Home & Kitchen',price:'$16–$24',moq:'30 units',image:'https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=900&q=80',source:'Global Sources',description:'High-speed countertop blender for home and commercial kitchens.',specs:['1200W motor','Multiple speeds','Steel blades','OEM branding'],unlock:2.5},
{id:5,name:'Black Desktop M-ATX Gaming PC Case',category:'Computer Hardware',price:'$7.31–$7.84',moq:'1 piece',image:'https://s.alicdn.com/@sc04/kf/H1b599e95c31b45478920469c25f972e4t.jpg_960x960q80.jpg',source:'Alibaba',description:'Mid-tower desktop PC case supporting MicroATX/ITX motherboards.',specs:['MicroATX/ITX','Mid Tower','Steel/Metal/Aluminum/Acrylic/Plastic','Audio + USB ports','3.55 kg package'],unlock:2.5,bigDeal:true},
{id:6,name:'DDR3 4GB Desktop/Laptop RAM',category:'Computer Memory',price:'$8.00',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR3 4GB memory module from the uploaded supplier catalog.',specs:['DDR3','4GB capacity','Supplier-listed price $8.00'],unlock:2.5,bigDeal:true},
{id:7,name:'DDR3 8GB RAM — 16 chips',category:'Computer Memory',price:'$12.50',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR3 8GB memory module, 16-chip option from the uploaded supplier catalog.',specs:['DDR3','8GB capacity','16 chips','Supplier-listed price $12.50'],unlock:2.5,bigDeal:true},
{id:8,name:'DDR3 8GB RAM — 8 chips',category:'Computer Memory',price:'$12.00',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR3 8GB memory module, 8-chip option from the uploaded supplier catalog.',specs:['DDR3','8GB capacity','8 chips','Supplier-listed price $12.00'],unlock:2.5,bigDeal:true},
{id:9,name:'DDR4 4GB RAM',category:'Computer Memory',price:'$25–$27',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR4 4GB memory with 2666 and 3200 speed options.',specs:['DDR4','4GB capacity','2666 MHz: $25','3200 MHz: $27'],unlock:2.5},
{id:10,name:'DDR4 8GB RAM',category:'Computer Memory',price:'$40–$45',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR4 8GB memory with compatibility and Intel-specific price options.',specs:['DDR4','8GB capacity','2666 MHz: $40–$42','3200 MHz: $43–$45'],unlock:2.5},
{id:11,name:'DDR4 16GB RAM',category:'Computer Memory',price:'$78–$85',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR4 16GB memory with 2666 and 3200 speed options.',specs:['DDR4','16GB capacity','2666 MHz: $78–$80','3200 MHz: $83–$85'],unlock:2.5},
{id:12,name:'DDR4 32GB RAM',category:'Computer Memory',price:'$158–$165',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR4 32GB memory with 8-chip and 16-chip compatible options.',specs:['DDR4','32GB capacity','8-chip compatible: $158','16-chip compatible: $165'],unlock:2.5},
{id:13,name:'DDR5 8GB RAM',category:'Computer Memory',price:'$100–$105',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR5 8GB memory with 4800, 5600 and 6000 speed options.',specs:['DDR5','8GB capacity','4800 MHz: $100','5600 MHz: $103','6000 MHz: $105'],unlock:2.5},
{id:14,name:'DDR5 16GB RAM',category:'Computer Memory',price:'$165–$195',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR5 16GB memory with 4800, 5600 and 6000 speed options.',specs:['DDR5','16GB capacity','4800 MHz: $165','5600 MHz: $185','6000 MHz: $195'],unlock:2.5},
{id:15,name:'DDR5 32GB RAM',category:'Computer Memory',price:'$310–$340',moq:'Ask supplier',image:memoryImg,source:'Alibaba',description:'DDR5 32GB memory with 4800, 5600 and 6000 speed options.',specs:['DDR5','32GB capacity','4800 MHz: $310','5600 MHz: $330','6000 MHz: $340'],unlock:2.5}
];
export default function App(){const[page,setPage]=useState('home'),[q,setQ]=useState(''),[cat,setCat]=useState('All'),[selected,setSelected]=useState<P|null>(null),[info,setInfo]=useState<I|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);const filtered=useMemo(()=>products.filter(p=>(cat==='All'||p.category===cat)&&(p.name+p.category+p.description).toLowerCase().includes(q.toLowerCase())),[q,cat]);const go=(x:string)=>setPage(x);useEffect(()=>{const x=new URLSearchParams(location.search),id=x.get('productId'),sid=x.get('session_id');if(x.get('payment')==='success'&&id&&sid){setLoading(true);fetch('/api/unlock-product',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:id,sessionId:sid})}).then(r=>r.json()).then(d=>{if(d.supplier){setInfo(d);setSelected(products.find(p=>String(p.id)===id)||null);setNotice('Payment verified — supplier access unlocked.')}else setNotice(d.error||'Payment verification failed.')}).catch(()=>setNotice('Payment verification failed.')).finally(()=>setLoading(false))}},[]);const checkout=async(p:P)=>{setLoading(true);try{const r=await fetch('/api/create-checkout-session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({productId:p.id})}),d=await r.json();if(!r.ok)throw Error(d.error);location.href=d.url}catch(e){setNotice(e instanceof Error?e.message:'Checkout failed');setLoading(false)}};return <div className="app"><header><div className="brand" onClick={()=>go('home')}><span className="logo">CS</span><div><b>ChinaSource Hub</b><small>Global China Sourcing</small></div></div><nav><button onClick={()=>go('products')}>Products</button><button onClick={()=>go('services')}>Services</button><button onClick={()=>go('how')}>How it works</button><button onClick={()=>go('request')}>Request a Quote</button></nav></header>{notice&&<div className="notice">{notice}</div>}{loading&&<div className="notice">Processing securely…</div>}{page==='home'?<Home go={go}/>:page==='products'?<main className="page"><div className="pageHead"><span className="eyebrow">PRODUCT CATALOG</span><h1>China-sourced products</h1><p>Compare sourcing opportunities. Supplier identity and direct links stay private until verified payment.</p></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/><select value={cat} onChange={e=>setCat(e.target.value)}>{['All',...Array.from(new Set(products.map(p=>p.category)))].map(c=><option key={c}>{c}</option>)}</select></div><div className="grid">{filtered.map(p=><Card key={p.id} p={p} open={()=>{setInfo(null);setSelected(p)}}/>)}</div></main>:page==='services'?<Services/>:page==='how'?<How/>:<Request/>}{selected&&<Modal p={selected} info={info} close={()=>{setSelected(null);setInfo(null)}} checkout={checkout}/>}<footer><b>ChinaSource Hub</b><p>Your bridge to reliable China sourcing for buyers worldwide.</p></footer></div>}
function Home({go}:{go:(x:string)=>void}){return <><section className="hero"><div><span className="eyebrow">GLOBAL SOURCING · CHINA</span><h1>Discover products from China. <em>Source with confidence.</em></h1><p>Browse curated products and unlock supplier information when you are ready to buy.</p><button className="primary" onClick={()=>go('products')}>Browse Products →</button></div></section><section className="section"><div className="sectionHead"><h2>Source-ready products</h2><button onClick={()=>go('products')}>View all →</button></div><div className="grid">{products.slice(0,6).map(p=><Card key={p.id} p={p} open={()=>go('products')}/>)}</div></section></>}
function Card({p,open}:{p:P;open:()=>void}){return <article className="card">{p.bigDeal&&<div className="dealBadge">🔥 BIG DEAL</div>}<img src={p.image}/><div className="cardBody"><span className="tag">{p.category}</span><h3>{p.name}</h3><p>{p.description}</p><div className="meta"><b>{p.price}</b><span>MOQ {p.moq}</span></div><div className="private">🔒 Supplier details protected</div><button className="primary full" onClick={open}>View & Unlock Supplier</button></div></article>}
function Modal({p,info,close,checkout}:{p:P;info:I|null;close:()=>void;checkout:(p:P)=>void}){return <div className="overlay" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="x" onClick={close}>×</button><img src={p.image}/><div className="modalText">{p.bigDeal&&<div className="dealBadge inline">🔥 BIG DEAL</div>}<span className="tag">{p.source} · {p.category}</span><h2>{p.name}</h2><p>{p.description}</p><h4>Key specifications</h4><ul>{p.specs.map(s=><li key={s}>{s}</li>)}</ul><div className="supplierBox">{info?<><b>✓ Supplier access unlocked</b><p><strong>{info.supplier}</strong><br/>{info.address}</p><a href={info.url} target="_blank" rel="noreferrer">Open original supplier marketplace →</a></>:<><b>Supplier identity protected</b><p>Supplier name, address and direct listing are hidden until your payment is verified.</p><button className="primary full" onClick={()=>checkout(p)}>Pay ${p.unlock.toFixed(2)} · Unlock Supplier</button><small>Secure payment powered by Stripe.</small></>}</div></div></div></div>}
function Services(){return <main className="page"><div className="pageHead"><span className="eyebrow">SERVICES</span><h1>From product discovery to supplier access.</h1></div></main>};function How(){return <main className="page"><div className="pageHead"><span className="eyebrow">HOW IT WORKS</span><h1>Browse → Evaluate → Pay → Buy direct</h1><p>Stripe verifies payment before private supplier data is returned.</p></div></main>};function Request(){return <main className="page"><div className="pageHead"><span className="eyebrow">REQUEST A QUOTE</span><h1>Tell us what you want to source.</h1><p>Send your product requirements and we can research suitable Chinese suppliers.</p></div></main>}