import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {onAuthStateChanged,signInWithEmailAndPassword,createUserWithEmailAndPassword,signInWithPopup,signOut,updateProfile,User} from 'firebase/auth';
import {auth,googleProvider,firebaseConfigured} from './firebase';
import './index.css';
import App from './App';

function AuthPage(){
 const[mode,setMode]=useState<'login'|'signup'>('login');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(!auth||!firebaseConfigured){setError('Authentication is not configured yet. Add the Firebase VITE_* settings in Vercel.');return}setBusy(true);try{if(mode==='signup'){const c=await createUserWithEmailAndPassword(auth,email,password);if(name.trim())await updateProfile(c.user,{displayName:name.trim()})}else await signInWithEmailAndPassword(auth,email,password)}catch(err:any){setError(err?.code==='auth/invalid-credential'?'Incorrect email or password.':err?.code==='auth/email-already-in-use'?'An account already exists with this email.':err?.message||'Authentication failed.')}finally{setBusy(false)}};
 const google=async()=>{setError('');if(!auth||!firebaseConfigured){setError('Google authentication is not configured yet. Add the Firebase VITE_* settings in Vercel.');return}setBusy(true);try{await signInWithPopup(auth,googleProvider)}catch(err:any){setError(err?.message||'Google sign-in failed.')}finally{setBusy(false)}};
 return <div className="authShell"><div className="authBrand"><img src="/logo.webp" alt="ChinaSource Hub"/><span>ChinaSource Hub</span></div><div className="authCard"><span className="eyebrow">GLOBAL CHINA SOURCING</span><h1>{mode==='login'?'Welcome back':'Create your account'}</h1><p className="authIntro">{mode==='login'?'Sign in to access your China sourcing catalog.':'Join ChinaSource Hub to discover products and unlock supplier access.'}</p><button className="googleBtn" onClick={google} disabled={busy}><span className="googleG">G</span>Continue with Google</button><div className="divider"><span>or continue with email</span></div><form onSubmit={submit}>{mode==='signup'&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" autoComplete="name" required/></label>}<label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters" autoComplete={mode==='login'?'current-password':'new-password'} minLength={6} required/></label>{error&&<div className="authError">{error}</div>}<button className="primary authSubmit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><p className="switchAuth">{mode==='login'?"Don't have an account?":"Already have an account?"} <button onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?'Create one':'Sign in'}</button></p><small className="authTerms">By continuing, you agree to use ChinaSource Hub responsibly and keep your account secure.</small></div></div>
}
function Root(){const[user,setUser]=useState<User|null>(null);const[ready,setReady]=useState(false);useEffect(()=>{if(!auth){setReady(true);return}return onAuthStateChanged(auth,u=>{setUser(u);setReady(true)})},[]);if(!ready)return <div className="authLoading">Loading ChinaSource Hub…</div>;if(!firebaseConfigured)return <AuthPage/>;return user?<div><div className="accountBar"><span>Signed in as <b>{user.displayName||user.email}</b></span><button onClick={()=>signOut(auth!)}>Sign out</button></div><App/></div>:<AuthPage/>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Root/></React.StrictMode>);
