import type {Product} from './products';
export const productData7:Product[]=[
{id:241,name:'150W Dimmable LED UFO Warehouse High Bay Light Fixture',category:'Lighting & Energy',price:'US$14.50-17.50',moq:'Min. order: 100 pieces',image:'https://image.made-in-china.com/2f0j00hEqcKfQCJoVr/150W-Dimmable-LED-UFO-Warehouse-High-Bay-Light-Fixture.webp',source:'Made-in-China',unlock:2.5,bigDeal:true},
{id:242,name:'20W 30W LED Integrated Outdoor Turbine Street Garden Road Home Street Light with Panel and Lithium Battery',category:'Lighting & Energy',price:'US$19.90-59.90',moq:'Min. order: 50 pieces',image:'https://image.made-in-china.com/202f0j00LwuotPZnLJbg/20W-30W-LED-Integrated-Outdoor-Turbine-Street-Garden-Road-Home-Street-Light-with-Panel-and-Lithium-Battery.webp',source:'Made-in-China',unlock:2.5,bigDeal:true},
{id:243,name:'Magnetic Track Light with CE and RoHS Certifications',category:'Lighting & Energy',price:'US$9.00-10.00',moq:'Min. order: 1 piece',image:'https://image.made-in-china.com/202f0j00kqjbiRKnMmct/Magnetic-Track-Light-with-CE-and-RoHS-Certifications.webp',source:'Made-in-China',unlock:2.5},
{id:244,name:'Z6 Model 3000W Lead Acid Battery 12 Inch or 14 Inch Motor Electric Mobility High Speed Scooter',category:'Electric Mobility',price:'US$400.00-500.00',moq:'Min. order: 10 pieces',image:'https://image.made-in-china.com/202f0j00tEABQNolZDbj/Z6-Model-3000W-Lead-Acid-Battery-12-Inch-or-14-Inch-Motor-Electric-Mobility-High-Speed-Scooter.webp',source:'Made-in-China',unlock:2.5,bigDeal:true},
{id:245,name:'Tuya WiFi Zigbee 3.0 Integrated Domotic Smart Home Automation System Products Devices Work with Alexa and Google Home',category:'Smart Home',price:'US$1.00',moq:'Min. order: 10 pieces',image:'https://image.made-in-china.com/318f0j00rQMGucbKOkoa/video-mp4.webp',source:'Made-in-China',unlock:2.5},
{id:246,name:'Smart Tuya WiFi Enabled Home Wall Mounted Air Purifier with HEPA Filter UV Light Anion',category:'Smart Home',price:'US$85.00-89.00',moq:'Min. order: 1 piece',image:'https://image.made-in-china.com/318f0j00eaYRoDHEubqP/KJ400wallmountedairpurifier-mp4.webp',source:'Made-in-China',unlock:2.5},
{id:247,name:'Free Shipping 25 Years Warranty 395W 400W 410W 420W Monocrystalline Perc Solar Panel',category:'Solar & Energy',price:'US$0.06-0.10 per Watt',moq:'Min. order: 1 Watt',image:'https://image.made-in-china.com/202f0j00dCUkKYwaAVcz/Free-Shipping-25-Years-Warranty-395W-400W-410W-420W-Monocrystalline-Perc-Solar-Panel.webp',source:'Made-in-China',unlock:2.5,bigDeal:true},
];
