import {productData1} from './product-data-1';
import {productData2} from './product-data-2';
import {productData3} from './product-data-3';
import {productData4} from './product-data-4';
import {productData5} from './product-data-5';
import {productData6} from './product-data-6';
import {productData7} from './product-data-7';
import {productData8} from './product-data-8';
import {productData9} from './product-data-9';
import {productData10} from './product-data-10';
import {productData11} from './product-data-11';
import {productData12} from './product-data-12';
import {productData13} from './product-data-13';
import {productData14} from './product-data-14';
import {productData15} from './product-data-15';
import {productData16} from './product-data-16';
export type Product={id:number;name:string;category:string;price:string;moq:string;image:string;source:string;unlock:number;bigDeal?:boolean};
export const products:Product[]=[...productData1,...productData2,...productData3,...productData4,...productData5,...productData6,...productData7,...productData8,...productData9,...productData10,...productData11,...productData12,...productData13,...productData14,...productData15,...productData16];
